### ISSUE TITLE
How about making a release on PyPI?

### ISSUE THREAD

**Issue by deeplook** [vmware/tern#136]
Being able to `pip install tern` would be so much more user-friendly.

**Comment by nishakm** [comment]
Definitely something to consider! I haven't made a release that way because there isn't anyone to manage the PyPl distribution. Git clone and setting up the virtual environment is the most KISS way to have the thing running without any build and release pipeline. There is an issue filed to create an install script: https://github.com/vmware/tern/issues/21. Would you consider taking it on. There is a bootstrap script for the Vagrant setup that could either be directly used or created into said install script.

**Comment by deeplook** [comment]
Frankly, I can't remember the last time I've used unpackaged code, i.e. not installable via setup.py and with pip at least from some hoster like github. Except when I really had to, and that's not the case for tern. If you want people to try this out and make them use it, packaging it up is the only way. You can find nice example templates at https://cookiecutter.readthedocs.io.

**Comment by nishakm** [comment]
Thanks for the suggestion and resources! Due to the reliance on the Docker CLI, it'll take a little work to get it there. But that's the goal for the next release, so will definitely be working on it.
