### ISSUE TITLE
Remove transitive dependencies

### ISSUE THREAD

**Issue by ericwb** [vmware/tern#208]
**Describe the bug**
The requirements.txt states six is needed, but I don't see any code using it.  Also the setup.py classifies as Py3 module.

**To Reproduce**
1. Go to requirements.txt
2. Note that six is listed

**Expected behavior**
Unused dependency wouldn't be in requirements.txt

**Environment you are running Tern on**
n/a

**Comment by nishakm** [comment]
`six` is a dependency pulled in by `docker`. `pip install --no-deps` might work.

**Comment by mkrohan** [comment]
I feel transitive dependencies should not be listed in the requirements file.  Only the direct dependencies used by tern should be listed, i.e., as far as I can tell, just,
```
docker==3.7.0
PyYAML==3.13
requests==2.21.0
```
The rationale here is to simplify updating dependencies via `pip list -o`.  If the full `pip freeze` list is committed, it's not clear if an out of date dependency can be updated, i.e., is the out of date dependency a transitive dependency that maybe should not be updated (the package pulling it in might not be ready for the updates in it).

Just fyi, the current out of date list is
```
$ pip list -o
Package Version Latest Type 
------- ------- ------ -----
docker  3.7.0   3.7.2  wheel
PyYAML  3.13    5.1    sdist
```

Note, the update for PyYAML will require some code changes to specify the style of loading needed (generates warnings rather than failing).

**Comment by nishakm** [comment]
Direct dependencies are only `PyYAML ` and `docker`. I'd actually be fine with removing all the transitive dependencies as it's misleading.

**Comment by mkrohan** [comment]
Do you want to assign this to me and I'll update it.  Looks like tern/utils/container.py includes a reference to the requests package.
