### ISSUE TITLE
Allow linting of commit messages

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#301]
**Describe the Feature**
In a CI/CD pipeline, test for commit message format.

**Use Cases**
This is useful for maintainers. Commit messages are formatted differently on the GitHub UI and so it's hard to review the original commit message format using the UI.

**Implementation Changes**
There are no available GitHub apps that help with this. So a developer tool needs to be created. This is also helpful during local development.
1. Create tool to check commit message format
2. Enable tool in CircleCI

**Comment by rnjudge** [comment]
There is a circleci orb to help with this: https://circleci.com/orbs/registry/orb/orbss/git_commit-message-validator

**Comment by rnjudge** [comment]
Nisha and I looked at the possibility of using two orbs:

1)  https://circleci.com/orbs/registry/orb/orbss/git_commit-message-validator
We concluded that this was not going to work because there was no way to provide informative feedback to the committer. There was only a way to give a generic error message.

2) https://circleci.com/orbs/registry/orb/dialogue/git
This orb required us to provide a commit message which would require additional tooling.
