### ISSUE TITLE
Randomly generate image and container names.

### ISSUE THREAD

**Issue by johnmm** [vmware/tern#74]
Currently, Image and Container names are not random. This should be updated to prevent any possible conflicts.

Some ideas:
- Using tern's PID
- Using a random number generator

We should be randomly generating names for:
- Docker image
- Docker image tag
- Docker container name

Currently https://github.com/vmware/tern/blob/master/utils/constants.py contains all the default names.
- Change the names into a prefix: ternimage and terncontainer
- Add a random number at the end of these
- Create a random number for the ternimage tag

Create a function in utils/general.py to randomly generate these names

Things to consider:
The names of the image, tag and the container are used in various parts of the project. There needs to be some central place where the other functions can access these names. Because they are persistent they cannot be regenerated during the course of execution.

**Comment by nishakm** [comment]
@johnmm Thank you! Do you think you can work on this?

**Comment by nishakm** [comment]
@johnmm, I would rather have something like tern_image_**random_no** and tern_container_**random_no**. Using the PID is fine although I wonder why you went to that proposal rather than just use a random number generator.

I will add some specs to this issue so you have some more direction. Thanks for taking it on!
