### ISSUE TITLE
Deep comparison of Package objects

### ISSUE THREAD

**Issue by nishakm** [vmware/tern#78]
Currently, comparisons of Package objects are only done based on name
```
p1 = Package(pkg_name1)
p2 = Package(pkg_name2)
if p1.pkg_name1 == p2.pkg_name2:
    # we assume this is enough to say that the two packages are equal but they are not!
```

Add a method (`def is_equal(self, another_pkg_obj)`) that will do a deep comparison of the package object
```
if self.name == another_pkg_obj.name and self.license == another_pkg_obj.licence ...
    return True
else
   return False
```

**Comment by nishakm** [comment]
@johnmm Do you think you can work on this one? It's quite straightforward.

**Comment by nishakm** [comment]
@johnmm do you still want to work on this? I'll probably need to take it off your hands in a week or so.

**Comment by johnmm** [comment]
@nishakm Sorry, I have been swamped with school work and regular work lately. I'm just getting back around to this.

I have made and unit tested the is_equal function and I'm trying to identify all the areas that need to be stepped up. Please let me know if this list seems complete to you.

Image_Layer.remove_package and Image_Layer.add_package seem to be the only direct impacts, but only remove_package will have outside impacts.

Changing remove_package impacts common.update_master_list which will ripple out to report.analyze_docker_image.

My proposed fix for this is to add a function to Image_Layer, get_packages, which will return the list of packages for the given Image_Layer. This means that the master_list from report.analyze_docker_image will be a list of package objects instead of package names. This should hopefully minimize impacts and allow us to keep most of the current logic in place.  

Tests for all of these areas will also need to be updated for this change.

If this solution sounds acceptable to you, I should be able to submit a pull request this week.

**Comment by nishakm** [comment]
@johnmm, don't worry! The project has a lot of work needed, and if not this one then there will be another one. I am so glad you want to put your time and effort into this and greatly appreciate it.

The is_equal function for the Package class will not be used by anything else in the project, so this change can stand by itself without breaking the code. If you are in doubt, just run the code against a docker image. You will have to install docker and pull and image from dockerhub first. See the README.md for a link to Docker's install page or CONTRIBUTING.md to see how to set up a Vagrant image.

At this point the unit test for Package may be failing (I have not paid attention to them yet). If you have a patch to also add a unit test for is_equal, that would be awesome!

image_layer.add_package and image_layer.remove_package does not compare the whole package object but just it's name and it uses the primitive == so there is no overriding involved like in C or C++. Like I said, they are safe to leave alone at this point. However, if you want to update them to use the is_equal to add a package object to the list or remove one from the list, please create an issue and add your notes to it, and then start working on it there. I don't think there is a need to modify the getter for the package list. I do want to encourage you to work on this at your own pace though. I don't want to be twisting your arm here :)

Let me know if you have any questions or need help. And once again, thanks for working on this!
